on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        protocol: ftps
        port: 21
        password: ${{ secrets.SFTP_PASSWORD }} #B4ZjkCKJCbHTPFa7
          # or use 'password:' instead of private-key if you must
        local-dir: ./              # change if you build to /dist or similar
        server-dir: /var/www/wwwroot/codexer.co.uk/
        log-level: verbose
